language: java
install: true
addons:
  sonarcloud:
    branches:
      - master
      - testbuild
    organization: mmirelli-github
    token:
      secure: "$TOKEN"
script:
- bash -e ./travis_build.sh
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
env:
  global:
  - secure: BNBYHiXiMdBnwutpYYAoMzYi+lxIDa5GQNkW2x2V8yY3sOBszo/nykcrOBO71C7veJFoMngPwqGS6re8o9JOdfVw0K74RURBBfRSzKQj/tJwsnP6ouPd58rn056IzDOSzscqbwDKczKA9O3IerE4tlSafEbju36bBESMZCl8QBTW0jOpxxbcbBeYW1c8zHbhPbvsdHwnMFItBvJXETGZ55CTvDsOIBGESev+cIap2QarFrcOU9Rcwvgaq+SOK1zV4Nc0zOuHhcKDXmvcgvP6rH5A84x6VEP8AqAVqu8Pg64aha/WwP069BsPHtLTJjQ9GIwLAK42Cp2XaWEqk05oXwc+isVZ7GNesJ/4w8OCZmc6PTdkVqHUXXOFHYfNQwn0dQoS6FupHymRsjjHAkuCR14rYdimBVWagBsGIRD9rtR/jAXhjCStpF+0kMdgPmv+QfQMWO9NpUPyhzLdbMuy2y9hQMtAsF1F9ySdNz4Y4u2RxoaE3RybIckJ4FEZd3chX0NdkVI0jQXJj1UFNAuWX+40QyzzPtNjZr4COBGFTn3GDttK1ZHdVQrFcogs/Dh3fceMZOfUDtEEe49dMkB2AOou4vP5R1YcZojMV6UUrEZBOf1eNicBSm6aBI4SYFRKTC0m5T+Sr8ixC5J3ir24sbqJOEA30H/PqdSvmsSV/lA=
