language: java
install: true
addons:
  sonarcloud:
    branches:
      - master
      - testbuild
    organization: mmirelli-github
    token:
      secure: "$TOKEN"
script:
- bash -e ./travis_build.sh
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
env:
  global:
    secure: QAwINmVEcpHeJ96cXPj+wB6qsanirawjOFT0/l0FdYaS4wXRed0XJfiXl0GNIqfMm2sn2lYkFtMCwYYVYkhrNzQij/3rueAQ2+5PdDxhkf9IyPxY6HaDWzwpKqqmHULw7GGSSVwo8C5h9dcxEZFP9X3JAW/gAAsTWiKUWCm/b01SmIH/PO8HziF9f5unoQ9s54KlHZp/10HnagJzWshpnvMqhfVkO+eoUT7IjF5hI8PtXxuA/QN4LYCvGHakLofNOnOFz+I21tyaSkqgWFy7lILQc7slJ+Hp6psJRjloadKDyLPNbXkY6MVufT2bxF6FVB/1d7FovQAmUnAuaCRCx72WV1zao39WIM5PxaJolwVQ8HkhbzpxmstqKuzpxu+8EzmtaMWp3t1JBMlSQsEblV2KwuAMq5HZnWtmEtU6GeB6YCb/yODKUjxQU8rsXXrsTg2j/cdnbqw2r/ar4H7FtGCysqsNK2wf33qC9uZ+EmSdlcpmSrOLWfHcrqb+wu+IQKTS3HOaAMH+pdT52OZP5rfJ/nPvx5CDvtgeKogmiFI9oy8RhZ1t2ceIhQ/icqNaaf7HwGH4LDShJgUUb2aoIhL5MhELWFLdyXES3hNdND6JGGSrtLL+lxUxiNHFZmaC1fb9f7H/RESwU6E2QH9t5ADOuxOxd1/OXIJwPFyDbB0=