drop table if exists STUDENT
drop table if exists STUDENT
drop table if exists STUDENT
drop table if exists STUDENT
drop table if exists STUDENT
drop table if exists STUDENT
drop table if exists STUDENT
drop table if exists STUDENT
drop table if exists STUDENT
drop table if exists STUDENT
drop table if exists STUDENT
drop table if exists STUDENT
drop table if exists STUDENT
drop table if exists STUDENT
drop table if exists STUDENT
drop table if exists STUDENT
drop table if exists STUDENT
drop table if exists STUDENT
